HeadHunter API Service
TalismanovAleksandr/JobHelperCore pull request #1
Opened 2022-02-18 16:04 UTC by vibezzz

2022-02-18 19:49 UTC, ryletka commented on src/main/java/ru/talismanandco/jobhelpercore/dto/HeadHunterSkill.java
> +    String name;
в большинстве случаев на все поля класса всегда вешается модификатор private

2022-02-18 19:55 UTC, ryletka commented on src/main/java/ru/talismanandco/jobhelpercore/dto/HeadHunterSalary.java
> +    Float from,to;
деньги обычно в BigDecimal

2022-02-18 19:57 UTC, ryletka commented on src/main/java/ru/talismanandco/jobhelpercore/dto/HeadHunterVacancy.java
> +    List<String> keySkills = new ArrayList<>();
я бы сделал `List <HeadHunterSkill>`
не нужен JsonSetter и лист ньюкать не надо

2022-02-18 20:00 UTC, ryletka commented on src/main/java/ru/talismanandco/jobhelpercore/service/HeadHunterApiService.java
> +        URIBuilder uriBuilder = new URIBuilder("https://api.hh.ru/vacancies");
в константу
`private static final String VACANCIES_ADDRESS = "https://api.hh.ru/vacancies";`

2022-02-18 20:01 UTC, ryletka commented on src/main/java/ru/talismanandco/jobhelpercore/service/HeadHunterApiService.java
> +        ObjectMapper mapper = new ObjectMapper().configure(
не нужно каждый раз создавать маппер, можно один раз создать и пользоваться везде, он thread-safe

2022-02-18 20:02 UTC, TalismanovAleksandr commented on src/main/java/ru/talismanandco/jobhelpercore/dto/HeadHunterSkill.java
> +    String name;
да, поля должны быть private. а @Data сгенерит public геттеры и сеттеры

2022-02-18 20:04 UTC, TalismanovAleksandr commented on src/main/java/ru/talismanandco/jobhelpercore/dto/HeadHunterSalary.java
> +    Float from,to;
на одной строке лучше не писать. + private + Ваня прав, если там числа с плавающей точкой, то BigDecimal, но тут разве не int? надо посмотреть и обсудить

2022-02-18 20:06 UTC, TalismanovAleksandr commented on src/main/java/ru/talismanandco/jobhelpercore/dto/HeadHunterVacancy.java
> +    List<String> keySkills = new ArrayList<>();
в данном случае мы говорим о скиллах типа "Java", "Spring", "Git". К хедхантеру не особо относится, возможно сделаем сложную структуру позже

2022-02-18 20:06 UTC, TalismanovAleksandr commented on src/main/java/ru/talismanandco/jobhelpercore/service/HeadHunterApiService.java
> +        URIBuilder uriBuilder = new URIBuilder("https://api.hh.ru/vacancies");
+

2022-02-18 20:06 UTC, TalismanovAleksandr commented on src/main/java/ru/talismanandco/jobhelpercore/service/HeadHunterApiService.java
> +        ObjectMapper mapper = new ObjectMapper().configure(
да, пока в поле класса, потом сделаем его синглтоном с помощью спринг за стримах

2022-02-18 20:08 UTC, ryletka commented on src/test/java/ru/talismanandco/jobhelpercore/service/HeadHunterApiServiceTest.java
> +        List<?> vacancies = headHunterApiService.getVacancies("Java", "0","5");
тест должен проверять что-то, каждый раз не будешь проверять глазами, что он там напечатал)
тут хотя бы надо использовать assertDoesNotThrow, чтобы проеврить что он не выкинул исключение
так как он тут реально вызывает HH, то мы не можем проверить конкретные значения того, что вернулось
можно на null проверить еще. А вообще нужно будет допилить класс и исользовать Mockito, но это Саня думаю расскажет попозже

2022-02-18 20:12 UTC, TalismanovAleksandr requested changes
Молодец, но нужны правки согласно моим комментам и ryletka

2022-02-18 20:12 UTC, TalismanovAleksandr commented on src/main/java/ru/talismanandco/jobhelpercore/dto/HeadHunterVacancies.java
> +    Integer found, pages, page,per_page;
не экономим бумагу(строчки). Лучше на новых строках)

2022-02-18 20:12 UTC, TalismanovAleksandr commented on src/main/java/ru/talismanandco/jobhelpercore/service/HeadHunterApiService.java
> +            e.printStackTrace();
тут потом понадобится log.debug

2022-02-18 20:12 UTC, TalismanovAleksandr commented on src/test/java/ru/talismanandco/jobhelpercore/service/HeadHunterApiServiceTest.java
> +                            (vacancy.getSalary()!=null?(
тернарным оператором сложно читается, лучше на if else переписать

2022-02-18 20:12 UTC, TalismanovAleksandr commented on src/test/java/ru/talismanandco/jobhelpercore/service/HeadHunterApiServiceTest.java
> +                vacancy.getKeySkills().forEach((String skill)->System.out.println(skill));
поменять или на skill ->System.out.println(skill) или лучше на System.out::println

2022-02-19 17:07 UTC, TalismanovAleksandr approved these changes

2022-02-19 17:08 UTC, merged